### ISSUE TITLE
`\tl_replace_all:Nnn` fails with a tl variable which contains `\q_mark` or `\q_stop`

### ISSUE THREAD

**Issue by qinglee** [latex3/svn-mirror#151]
\RequirePackage{expl3}
    \ExplSyntaxOn
    \tl_set:Nn \l_tmpa_tl { \q_mark }
    \tl_replace_all:Nnn \l_tmpa_tl { a } { A }
    \tl_show:N \l_tmpa_tl
    \tex_end:D

There would be an endless loop.

**Comment by josephwright** [comment]
@blefloch fixed this in that commit (but didn't' put `fixes #151` or similar) :-)
