### ISSUE TITLE
\tl_set_rescan:Nnn drops trailing spaces

### ISSUE THREAD

**Issue by josephwright** [latex3/svn-mirror#154]
As mentioned by egreg in http://chat.stackexchange.com/transcript/message/11364273#11364273, the case
````
\documentclass{article}
\usepackage{expl3}
\ExplSyntaxOn
% avoid issues with catcodes
\cs_set_eq:NN \rescan \tl_set_rescan:Nnn
\ExplSyntaxOff
\begin{document}
\rescan\x{}{ab }
X\x X
\end{document}
````
fails as `\scantokens` drops the trailing (end of line) spaces. 

Fix in hand, at least for basic case, so will commit once fully tested.

**Comment by qinglee** [comment]
`\tl_set_rescan:Nnn` also drops leading spaces:

    \documentclass{article}
    \usepackage{expl3}
    \ExplSyntaxOn
    % avoid issues with catcodes
    \cs_set_eq:NN \rescan \tl_set_rescan:Nnn
    \ExplSyntaxOff
    \begin{document}
    \rescan\x{}{ ab }
    X\x X
    \end{document}

It's better to document it.

**Comment by blefloch** [comment]
Note to self: we can preserve leading spaces because TeX drops catcode 10 characters there.  Instead of directly applying `\scantokens`, pass the token list to `\tl_to_str:n`, then loop through the first few characters collecting catcode 10 characters and remove them from the token list passed to `\scantokens`.  Afterwards prepend a blank space token to the result if there was any catcode 10 char.

**Comment by blefloch** [comment]
The almost-complete solution taken in my upcoming commit is to find a character with catcode 11, 12, or 13 (letter, other, or active) and actually scan the string provided by the user followed by that character, then remove that character immediately followed by the rescan marker inserted by `\everyeof`.  This means that trailing spaces will be kept as long as there exists at least one character with a sensible catcode (11,12,13) in the ascii range [39,127] (almost all of ascii).  I call that a fix.  There remains an uncertainty about my choice of how to treat multi-line rescanned strings versus single-line rescanned strings.
