### ISSUE TITLE
Expandable errors for programmers

### ISSUE THREAD

**Issue by blefloch** [latex3/svn-mirror#172]
[Reading through old emails, this one from Feb 10, 2013.]

[A user](http://tex.stackexchange.com/q/97578/2707) wants to have the ability to trigger expandable errors.  We have the necessary code in l3msg.dtx, but it is currently an internal function, `\__msg_...`, hence is not to be used away from `l3kernel`.  I've already found the need to use it in packages that may very well not end up in the kernel, for instance, `l3bigint`.  As there is no simple alternative for packages that purport to provide expandable tools, we should provide access to that feature for package writers.  [Joseph and Will seemed to be in favor last year.]

I see three possible layouts.

(1) Choose whatever cs you like (\#^@ below), and use some ^^J to
separate the error from the TeX 'undefined cs' error. Write the module
name on the same line as the error message. Namely

    ! Undefined control sequence.
    <argument> \#^@

    ! siunitx error: foobar baz.

(2) Choose a relatively clear prefix, and produce

    ! Undefined control sequence.
    <argument> \__error:
                            siunitx: foobar baz.

(3) Use one undefined cs per module,

    ! Undefined control sequence.
    <argument> \ siunitx error:
                                foobar baz.

but this is trickier and costs two entries in the hash table per module.

**Comment by blefloch** [comment]
Option (3) requires package writers to declare in advance that they will need expandable errors (the undefined csname cannot be constructed on the fly with `\csname...\endcsname` as that would define it to `\relax`).  I think it is not good.

Option (1) (using `^^J` to force the error message into a new line) fails in XeTeX: one gets two `^` and one `J` instead of a newline.

If no one complains, I'll implement option (2) with the undefined control sequence `\_@@_/` or whatever inspires me at the time of implementation.

I could have slightly different layouts in the different engines, using `^^J` in pdfTeX and using Lua code in LuaTeX, but that makes the job of editor programmers more difficult, so I'm thinking of not doing that.

**Comment by josephwright** [comment]
This is quite a specialised requirement so I'd not go overboard. Option (2) looks a reasonable balance to me: we do make the ability available that way but it's not too complex.

**Comment by FrankMittelbach** [comment]
Am 31.07.15 um 19:08 schrieb Bruno Le Floch:
> If no one complains, I'll implement option (2) with the undefined 
> control sequence |\_@@_/| or whatever inspires me at the time of 
> implementation.

I would go for something still descriptive, e.g.

\__EXPL_MODULE_ERROR__/

or without the EXPL

**Comment by blefloch** [comment]
I should have been more explicit in my reasons to take a short name: every character in the command name is one character less that the error message itself can use.  What about `\__error:` ?  The drawback is that we need to register that prefix then.

**Comment by blefloch** [comment]
I've gone for `\::error` for no particular reason.  I'm happy to change that.
