### ISSUE TITLE
Wrong links if pdflatex is run only once before makeindex

### ISSUE THREAD

**Issue by blefloch** [latex3/svn-mirror#188]
If `\tn` or `\cs` or `\cmd` is used inside a `\section` or a similar place which ends up being typeset only on the second run, then all subsequent links from the index to the main text point to the wrong target (shfted)

    \documentclass{l3doc}
    \begin{document}
    \tableofcontents
    \section{About \tn{write}}
    Also about \tn{read}.
    \PrintIndex
    \end{document}

Running `pdflatex`, `pdflatex`, `makeindex`, `pdflatex`, `pdflatex` correctly gives three entries in the index: one `\write` pointing to the table of contents, one pointing to the section title, and one for `\read` pointing to the text.

Running only `pdflatex`, `makeindex`, `pdflatex`, `pdflatex` as is done by `l3build` only gives two entries in the index (because `makeindex` cannot know about the table of contents), which point to the two `\write` instead of a `\write` and a `\read`.

**Comment by josephwright** [comment]
This got fixed a while ago.
