### ISSUE TITLE
\tl_if_eq_p:Vn variant is not working for me as I expect

### ISSUE THREAD

**Issue by benzea** [latex3/svn-mirror#201]
Hi,

I was trying to build a loop that tested a tokenlist variable against a passed argument. My idea for that was to simply generate the \tl_if_eq_p:Vn variant, and then do:

    \bool_until_do:nn { \tl_if_eq_p:Vn \g__mypackage_sometokenlist_tl { #1 } } { LOOP CODE }

However, this did not work for me. Instead using a \tl_if_eq:VnTF variant, setting a boolean variable inside and then testing against that works fine. The following code is a test case, simply change the used loop and the code fails to terminate:
https://gist.github.com/benzea/c6d145614b298bc13be1

Maybe I am doing something wrong here, but I don't understand why this would fail to work.

**Comment by josephwright** [comment]
You've got several things a bit off in your linked code. Taking the key part
````
\cs_generate_variant:Nn \tl_if_eq:nnTF { VnTF }
\cs_generate_variant:Nn \tl_if_eq_p:NN { Vn } 
````
the first line is OK (although `\cs_generate_variant:Nn \tl_if_eq:nnTF { Vn }` is the official way to do this), but the second is wrong. You cannot create an `n`-type variant of an `N`-type argument as they are both base types. You can make a `c`-type variant of an `N`-type argument, and a `V`-, `v`-, `f`-, `x`- or `o`-type variant of an `n`-type argument.

I suspect you want `\tl_if_eq_p:nn` and are not finding it. As predicate evaluation is expandable it can only work for expandable tests. The token list test `\tl_if_eq:nn(TF)` is not expandable (it requires an assignment) and so there is no predicate. You can use `\str_if_eq_p:nn`, which does a expandable string comparison or you need to arrange a non-expansion context where `\tl_if_eq:nn(TF)` can be used.

I'm not 100% sure I see what you want to achieve in the code in terms of outcome. Can you describe the overall aim and I'll suggest some code.

**Comment by benzea** [comment]
Aha! I do understand that it does make sense that `N` cannot be converted to `V` (if it is easy, I would suggest throwing an error if this happens).

You are right that I was basically looking for \tl_if_eq_p:nn and using \str_if_eq_p:nn might work for me. Though I haven't quite grasped the non-expansion context that you mentioned, I'll need to look into that.

On a high level, I want some context management that is independent of LaTeX groups. My idea was to keep a stack of "prop" variables (I serialize them into a list of tokens for the stack). By giving each stack frame a name the user has the possibility to pop multiple frames up to and including the one with a given name.

The full code is at https://github.com/sdaps/sdaps-class/blob/master/sdapsbase.dtx (\sdaps_context_begin_local: uses the feature to end the context when the group ends). There is some more unrelated code in there though (probably riddled with errors :-)).

Oh, I have to say that I really like LaTeX 3. I don't think I would have managed to get this far with LaTeX 2e.
