### ISSUE TITLE
l3build: support alternative makeindex executable

### ISSUE THREAD

**Issue by leo-liu** [latex3/svn-mirror#210]
When preparing our Chinese TeX bundles, we need to add some hooks to `l3build.lua`.

Thanks to the scoping rules of lua, we could hook the global functions in our `main` function, without knowing how the global functions are defined. However, I find it a bit difficult to configure the very long `doc()` function, since it uses local functions for typesetting.

By now we just need to change `makeindex` to our Chinese version `zhmakeindex`. But we had to copy the whole `doc()` function definition in our `build.lua` to make a change, and this might break when `l3build` updates its `doc()` function.

I think it would be great if there is a `makeindexexe` variable to specify an alternative makeindex executable.

**Comment by josephwright** [comment]
The 'long term' plan is to provide some richer mechanisms for dealing with the variation in typesetting that might be needed, for example a series of sub-functions properly described for setting up a typesetting routine. However, that is still evolving: I agree that this change would work well for the present. Expect a checkin soon.
