### ISSUE TITLE
Improve error when l3fp receives \sin instead of sin

### ISSUE THREAD

**Issue by blefloch** [latex3/svn-mirror#216]
When `amsmath` is loaded, `\fp_set:Nn \l_tmpa_fp { \sin(3) }` fails horribly (without `amsmath` it fails reasonably with just a couple errors).

    \RequirePackage{expl3,amsmath}
    \ExplSyntaxOn
    \fp_set:Nn \l_tmpa_fp { \sin(3) }

gives ten errors or so.  The first error is "Erroneous variable \protect used", due to `\protect` being `\relax`.  In package mode, it may make sense to detect this special case and give a better error message "Robust command used in l3fp expression" or similar?

A slightly different case is

    \fp_show:n { \sin(3) }

where `\protect` is `\noexpand\protect\noexpand`, and the `\notexpanded: \protect` confuses `l3fp` which expects to have expanded everything: `\ifcat` says that this `\protect` is a control sequence, while `\ifx` says it is not `\relax`, so `l3fp` concludes it must be a register.  It may be best to replace `\ifx#1\relax` by `\expandafter\ifx\noexpand#1\relax` so that expandable commands that snuck all the way to this stage give a LaTeX3 error rather than breaking when TeX acts with `\the` on them.

**Comment by josephwright** [comment]
This is an error either way, right? I guess if there is an easy way to give a better message then we should, but I would not make it a priority.

**Comment by blefloch** [comment]
Yes, I should have made it clearer, it is an error either way and it's not possible to avoid that.  The change I have in mind would give a somewhat meaningful error message whenever a robust command is encountered (but it would fail to clean up I think) or when `\noexpand` is used.
