### ISSUE TITLE
Add detail to xtemplate documentation

### ISSUE THREAD

**Issue by wspr** [latex3/svn-mirror#220]
See Ulrike's [comment](http://chat.stackexchange.com/transcript/message/22609397#22609397).

**Comment by josephwright** [comment]
Given that we know `xtemplate` is wrong (TUG2015 discussion) do we want to do this?

**Comment by FrankMittelbach** [comment]
On 24.07.2015 07:08, Joseph Wright wrote:
> Given that we know |xtemplate| is wrong (TUG2015 discussion) do we want
> to do this?

I think it is a waste of resources - needs rewriting anyway once we 
marry it with the ideas of LDB etc

**Comment by josephwright** [comment]
Agreed: close?

**Comment by wspr** [comment]
Thinking slightly more about the template concept, I wonder if it still makes sense to keep it for certain "context-free" situations even if the main approach is dropped in favour of LDB style sheets.

I'm thinking of examples like for the way that xfrac works, or a potential drop-caps package. 

In these cases you might not want the heavy lifting of LDB but still make use of the idea of instances and so on. Also allows us to stick with a small number of positional arguments. 

So if you like I'm happy to have this assigned to me, and clear up where we think XTEMPLATE still has use cases. Or we could close this issue here and continue the discussion else where if this isn't a convincing enough argument.

**Comment by u-fischer** [comment]
Imho as long as the package is around clear (and simple) errors in the documentation should be corrected: I was trying to figure out what the acro package is doing and had problems to understand the arguments. 

Apart from this xtemplate didn't really appeal to me, I doubt that I will use it.

**Comment by josephwright** [comment]
@u-fischer  I double checked the sources: the info is there but was not marked up correctly. I'll fix that (there is nothing new to actually write).
