### ISSUE TITLE
\scan_align_safe_stop: seems to be redundant

### ISSUE THREAD

**Issue by josephwright** [latex3/svn-mirror#224]
We have `\scan_align_safe_stop:` as we used to have a rather complex set up to try to keep expandability but allow `\mode_if_math:TF`, _etc._ However, we realised all of the 'fun' was pointless as it doesn't really work, so now just have a protected function. But under those circumstances why not just say functions have to be protected to work in the contexts this applies in.

**Comment by blefloch** [comment]
Agreed.  I fail to see any use case, and TeXLive has no valid use case.
