### ISSUE TITLE
Loading of package libraries in an expl3 context

### ISSUE THREAD

**Issue by u-fischer** [latex3/svn-mirror#235]
When expl3-syntax is activated you can nevertheless load other packages without problems.  This here does "the right thing":

~~~~~~
\ExplSyntaxOn
....
\usepackage{somepackage}
....
\ExplSyntaxOff
~~~~~~

But the same is not true when loading package "libraries". You can't use `\usetikzlibrary{positioning}` or
`\tcbuselibrary{skins}` (from tcolorbox) without getting errors. What can/should package authors do to make such library loading commands "expl3-safe"?

**Comment by josephwright** [comment]
Use the LaTeX2e `\@pushfilename`/`\@popfilename` stack. This is used by LaTeX2e for managing the catcode of `@` and is extended by us to also cover `expl3` syntax.

**Comment by u-fischer** [comment]
This obviously means that nobody really knows about this stack or there wouldn't be a problem. In both cases the code manage the saving of the catcode @ and the restoring manually. What about beamer themes? Do you know if they use the stack?

**Comment by josephwright** [comment]
Like many things, the stack was really meant to be part of the 'kernel internals', hence the fact it's not documented. Of course, the team ourselves (or at least some members: this trick pre-dates me on the team) do know these things. What is true is we can't really patch for all possible additional file loading mechanisms. I could look to see if we can include a hook for people, but they'd still need `expl3` to be loaded before our code.

**Comment by u-fischer** [comment]
I don't think there is a need for a hook -- after all the stack is there. It only needs to be made more known along with some description how to use it so that package authors with library input don't starts to write their own code to store and restore expl3 catcodes.  I'm just sending a mail to the tcolorbox author ...

**Comment by josephwright** [comment]
Thinking about it, package authors don't need to alter `\@pushfilenames`/`\@popfilenames`: they just need to include these in any file loading. See the 'official' use in `\@onefilewithoptions`.

**Comment by u-fischer** [comment]
That's what I thought you are suggesting anyway. This here works fine:

~~~~~
\csname @pushfilename\endcsname
\tcbuselibrary{skins}
\csname @popfilename\endcsname
~~~~~~

**Comment by josephwright** [comment]
Yes, that's exactly what I'm thinking.

**Comment by T-F-S** [comment]
I made a pre-release version (3.72pre1) for tcolorbox which uses the `\@pushfilename` / `\@popfilename` stack as suggested. This seems to work like expected. You can find this pre-release under https://github.com/T-F-S/tcolorbox.

**Comment by josephwright** [comment]
@u-fischer OK, so what action (if any) is needed at the `expl3` end?

**Comment by u-fischer** [comment]
@josephwright : Imho nothing beside some documentation and spreading around the news.  When I see packages which use such libraries I will try to tell them about this discussion.

**Comment by josephwright** [comment]
On that basis, and as this related to LaTeX2e internals, I'll close the issue (we can't actually do much at the `expl3` end).

**Comment by FrankMittelbach** [comment]
On 25.07.2015 20:23, Joseph Wright wrote:
> On that basis, and as this related to LaTeX2e internals, I'll close the
> issue (we can't actually do much at the |expl3| end).

well, we could think of writing a short article on filename stacks (or 
somebody :-) in TUB or in a blog entry or ...

**Comment by josephwright** [comment]
@FrankMittelbach OK, I'll write something more my blog (which I see as semi-official for this sort of thing)

**Comment by josephwright** [comment]
Blog post written: http://www.texdev.net/2015/07/30/making-custom-loaders-expl3-aware/. Comments, _etc._ welcome but I'm calling the issue closed.

**Comment by FrankMittelbach** [comment]
On 30.07.2015 21:36, Joseph Wright wrote:
> Blog post written:
> http://www.texdev.net/2015/07/30/making-custom-loaders-expl3-aware/.
> Comments, /etc./ welcome but I'm calling the issue closed.

thanks

**Comment by tohecz** [comment]
Well, it would be nice to have `\InputExplFile{bla.bla}`, which would input the file `bla.bla` with L3 catcodes, but after inputting it, it would restore the original catcodes. From what I understand, this is what the following does, right?

```
\csname @pushfilename\endcsname
\input{bla.bla}
\csname @popfilename\endcsname
```

**Comment by u-fischer** [comment]
As a side remark to tohecz comment I think that the description of \ProvidesExplPackage,
\ProvidesExplClass and \ProvidesExplFile in source3 is misleading. It says "At the end
of the file, \ExplSyntaxOff will be called to reverse this.". This only works if one load the file with \usepackage or \documentclass, but not for simple \input.

**Comment by lvjr** [comment]
Is there any harm to provide public commands `\PushFileName`/`\PopFileName` as an alias?

**Comment by u-fischer** [comment]
> @u-fischer Did you draw the attention of the `TikZ` team? 

I don't really remember ;-)


> Because the following fails

Yes, they are not using it.  You could open an issue at the tikz github.
