### ISSUE TITLE
\tl_case:Nnn undefined

### ISSUE THREAD

**Issue by zhouyan** [latex3/svn-mirror#237]
After the most recent TeXLive update, I am staring to seen the following error while using unicode-math package. This seems to relate to a change in l3kernel
```
! Undefined control sequence.
\um_set_mathsymbol:nNNn #1#2#3#4->\tl_case:Nnn 
                                               #3{\mathop {\um_set_big_opera...
```

**Comment by josephwright** [comment]
This is a deprecation we've had in the pipeline for some time. It needs to be fixed in `unicode-math` rather than `expl3`.
