### ISSUE TITLE
Error when loading expl3 is aborted

### ISSUE THREAD

**Issue by blefloch** [latex3/svn-mirror#238]
In `expl3-code.tex` there are tests for various primitives, and if absent, the code calls `\endinput` after telling the user that loading expl3 is aborted.  However, that brings the user back to the rest of `expl3-generic.tex` (or `expl3.sty`) which expects expl3 functions to be defined.  An artificial example is to run `pdftex` on

    \let\pdfstrcmp\relax
    \input expl3-generic\relax

A less artificial example is `fontinst expl3-generic` giving

    ! expl3 Error: Required primitives not found.
    \PackageError ...lp {#3}\errmessage {#1 Error: #2}
                                                       
    \next ...later.^^J^^JLoading of expl3 will abort!}
                                                      \endgroup \endinput 
    l.343 \next
               
    ? 
    )
    ! Undefined control sequence.
    l.100 \cs
             _set_eq:NN \__iow_wrap_set:Nx \tl_set:Nx

Presumably the fix is simply to put `\endinput\endinput` instead of a single `\endinput`, but I know that I will miss some places where this is needed.

**Comment by josephwright** [comment]
Well the idea was really that if loading aborts the user should take action at that stage: further errors are to be expected!

**Comment by blefloch** [comment]
By this logic, even the first `\endinput` is unnecessary, we could just let everything crash.  But so far we've usually been rather "polite", trying to crash with reasonable error messages, and preferably a single error.  I'll see what I can do, but it seems `\endinput\endinput` doesn't do the right thing (it closes the same file twice).
