### ISSUE TITLE
Test files m3expl001.lvt and m3expl004.lvt are redundant

### ISSUE THREAD

**Issue by blefloch** [latex3/svn-mirror#243]
The test files `m3expl001.lvt`, `m3expl002.lvt`, `m3expl003.lvt`, and `m3expl004.lvt` load `expl3.sty` with various options:

1. `\RequirePackage[log-functions]{expl3}`
2. `\RequirePackage[check-declarations]{expl3}`
3. `\RequirePackage[log-functions,check-declarations]{expl3}`
4. `\RequirePackage{expl3}`

The `check-declarations` option (which makes sure that variables are defined before being used) produces almost no output in the `log` file (it could only produce errors, and there are none of this type in `expl3.sty`).  Because of this, `m3expl001.tlg` and `m3expl003.tlg` only differ by a line,

    > Defining message LaTeX/check/non-declared-variable on line ...

similarly for `m3expl002.tlg` and `m3expl004.tlg`, and engine-specific tests.  Since the tests including `check-declarations` are more stringent than those without I'd like to only keep the `\RequirePackage[check-declarations]{expl3}` and `\RequirePackage[log-functions,check-declarations]{expl3}` test files.

**Comment by blefloch** [comment]
Forgot to mention pro and contra.

Pro: currently any time we define a new function, all six `tlg` files `m3expl001.tlg`, `m3expl001.xetex.tlg`, `m3expl001.luatex.tlg`, `m3expl003.tlg`, `m3expl003.xetex.tlg` and `m3expl003.luatex.tlg` change and must be at least roughly checked.  Removing one of `m3expl001` and `m3expl003` would halve that work.

Contra: we may miss weird bugs that only affect the version of commands defined without `check-declarations`.  That is already the case in other tests since all of them include `check-declarations`.

**Comment by FrankMittelbach** [comment]
Am 03.08.15 um 10:10 schrieb Bruno Le Floch:
> Since the tests including |check-declarations| are more stringent than 
> those without I'd like to only keep the 
> |\RequirePackage[check-declarations]{expl3}| and 
> |\RequirePackage[log-functions,check-declarations]{expl3}| test files.
I would keep them. They run different scenarios and experience has shown 
that it is good to have fixpoints for each (even if when everything is 
fine they show a subset of each other)

**Comment by josephwright** [comment]
The idea is to test every combination: whilst they _should_ be almost the same that's not the same as they _are_!

**Comment by blefloch** [comment]
You both have a good point.  I'll close this issue.
