### ISSUE TITLE
l3build: Parse command line optionals

### ISSUE THREAD

**Issue by josephwright** [latex3/svn-mirror#245]
It would be better to allow
```
build check --engine=pdftex foo
```
than the current
```
build check foo pdftex
```
This would also allow more options.

**Comment by josephwright** [comment]
OK, I see how to do this. The 'best' Lua implementation for argument parsing seems to be https://github.com/mpeterv/argparse, while @wspr  points to the much simpler https://www.ctan.org/pkg/lua-alt-getopt for just dealing with the optional part. I think we can avoid adding large amounts of third-party code by taking the tack that we can special-case things. My thinking:

 - We know `arg[1]` has to be the 'command' (to use the naming from `argparse`)
 - We are only likely to need to find a small number of optionals: `--engine` (= `-e`?), `--halt-on-error`/`--halt-on-failure` (= `-f`?) (plus I guess `--` for end-of-options) at this stage
 - We can turn all of that into a table with entries `command`, `engine`, `halt`, `files`, with the latter allowing us to add multi-file support to both `check` and `save`

**Comment by josephwright** [comment]
Probably `-H` is better for 'halt'

**Comment by FrankMittelbach** [comment]
Am 07.08.15 um 12:45 schrieb Joseph Wright:
> Probably |-H| is better for 'halt'

I would second that

**Comment by josephwright** [comment]
I have some code in-hand: just need to adjust how values are then passed to the rest of the build system.

**Comment by blefloch** [comment]
Why `-H` rather than `-h`? (Is the latter short for `--help`?)  Thinking of help, it's probably not completely useless to rethink the help text at some point and make it more informative: right now we only get the list of top-level commands.  Perhaps `texlua build.lua check --help` could give the syntax of check and a list of options like `--engine` etc.  This may be over the top.

**Comment by josephwright** [comment]
@blefloch  Indeed, `-h` is pretty-much universal for `--help` so I don't want to mess that up. I'll need to rejig the help a bit once I allow optionals using the 'normal' syntax, so if you fancy adding specific help for each command that's fine :-)
