### ISSUE TITLE
l3build: Option to halt on first failing test

### ISSUE THREAD

**Issue by josephwright** [latex3/svn-mirror#246]
It would sometimes be useful for the check system to halt on the first error: something like
```
build check --halt-on-error foo
```
which then requires optional arg parsing (see https://github.com/latex3/svn-mirror/issues/245).

**Comment by FrankMittelbach** [comment]
Am 06.08.15 um 10:03 schrieb Joseph Wright:
> It would sometimes be useful for the check system to halt on the first
> error: something like
>
> |build check --halt-on-error foo |
>
> which then requires optional arg parsing (see #245
> <https://github.com/latex3/svn-mirror/issues/245>).

probably, but I would suggest a short name like --halt

**Comment by josephwright** [comment]
@FrankMittelbach Was based on the same option for engines, but can be negotiated once I work out how to do the underlying option parsing.

**Comment by FrankMittelbach** [comment]
Am 06.08.15 um 10:14 schrieb Joseph Wright:
> @FrankMittelbach <https://github.com/FrankMittelbach> Was based on the
> same option for engines, but can be negotiated once I work out how to do
> the underlying option parsing.

that's an argument in favor of your name ... mine was that I'm lazy and 
don't like typing :-)

**Comment by josephwright** [comment]
As at @wspr  says, do we really need to run all of the tests once we know something fails: should we just stop anyway?

**Comment by wspr** [comment]
I'd be in favour of by default stopping after the first that doesn't validate. OTOH, when running 20 tests, say, and 3 isolated ones fail, it is kind of nice to have those three diffs all available for querying after the fact. So I think we need both `:)`

If you want a low-tech solution, could just have `build check` and `build checkall` to distinguish these cases.

**Comment by blefloch** [comment]
Can we also have a `saveall` target (or similar) that does `texlua build.lua save <testfile>` on each test file, but optimized to only unpack once?  Or something to only do that for some testfiles.  This would have been very useful to me when making changes to what packages send to the log.  The workflow then would be `saveall` then `svn diff` to check changes.

**Comment by josephwright** [comment]
@blefloch  I suspect that can be covered by just `save` if I can move the engine argument from the end to an optional: something like `save <file or files>` will then be possible. As already noted, I first need to look seriously at aoptparse/argparse like functionality.

**Comment by FrankMittelbach** [comment]
Am 06.08.15 um 10:43 schrieb Will Robertson:
> I'd be in favour of by default stopping after the first that doesn't
> validate. OTOH, when running 20 tests, say, and 3 isolated ones fail, it
> is kind of nice to have those three diffs all available for querying
> after the fact. So I think we need both |:)|

yes I  guess you need both but in my book the prio is the other way 
around. Normally when I make a change I want to see side by side what 
fails as often the first failure may not give enough info (so you are 
likely to start fixing it just to learn that there is another failure 
that invalids your approach)

So I'm more in favor of having the checkall being the default and the 
one that stops being the one that is extra
>
> If you want a low-tech solution, could just have |build check| and
> |build checkall| to distinguish these cases.

therefore the low-tech fr me would be

build check     -> check all list results
build checkstop -> stop checking on first failure

**Comment by josephwright** [comment]
I'm with @FrankMittelbach  on the default, hence suggesting `--halt-on-error` as an option. I think I can see how to implement this and `--engine` without needing 'full' argparse support ([available for Lua](https://github.com/mpeterv/argparse) but would mean adding a second Lua file as a dependency). The latter option might make more sense long-term, though, as it would mean we can continue to add options.

**Comment by wspr** [comment]
Agreed on the default as per Frank. Would prefer something less verbose than `--halt-on-error` though :)

Also agree with Bruno that `saveall` or similar would be useful. I'd be using it now to help migrate all my old `unicode-math` tests to my new build system, if it existed.

* * *

Regarding the default for checking and stopping (or not), I imagine that people's workflows (if they're anything like mine) are:

* edit package, fix some bugs
* `build check` (*does everything without stopping*)
* breaks N tests
* fix those new bugs
* `build check` (*everything now passes*)
* Futz around with document and code tidy-ups
* `build ctan`

Now here's the thing. When `build ctan` re-checks the test suite, I'd like to know ASAP that one of my tests failed, and if that happened, the workflow above would loop back to an earlier step. So I'd argue that when performing `build ctan`, the default should be `build checkstop` or `build check --halt-on-error` or whatever it ends up being called `:)`

Of course, you can shoot me down and I won't complain, but I might request mildly for a way to customise it in the `build.lua` file.

**Comment by josephwright** [comment]
All noted: I'll work on it over the coming days.

**Comment by josephwright** [comment]
As detailed in https://github.com/latex3/svn-mirror/issues/245#issuecomment-128608082, suggested naming here is `--halt-on-error`/`--halt-on-failure`/`-f`: anything better occur to anyone? As also noted there, adding `argparse`-like functionality will allow use to extend `check` and `save` targets to cover multiple files. (That will require some internal changes, so first I'll add the parsing and then deal with things in stages!)
