### ISSUE TITLE
l3styleguide on primitives

### ISSUE THREAD

**Issue by blefloch** [latex3/svn-mirror#256]
`l3styleguide` does not discuss what to do when a package author needs a primitive for which there is currently no `expl3` wrapper.  When that was discussed on the team list, my impression of the consensus was that the best practice is to copy the primitive, then use this in the rest of the code.

    \cs_new_eq:NN \@@_message:w \tex_message:D
    % ...
    \cs_new_protected:Npn \@@_fancy_msg:n #1 { \@@_message:w { *** #1 *** } }

If that is indeed the consensus, it should be documented.

**Comment by josephwright** [comment]
I'm happy to do this: I wrote the style guide.

**Comment by blefloch** [comment]
Thanks.  Can you also include the following mention?  That when people want an internal from another package (e.g., `\__prg_variable_get_type:N`) they should copy its definition into their package, so that if the implementation changes their package does not break.  And they should probably tell the other package writer (e.g., us) so that he/she knows that her/his code is used hence should be given a public interface (e.g., rename `\__prg_...` to `\prg_...`).

**Comment by FrankMittelbach** [comment]
my thoughts are that we should document that

a) we hope this is the exception as normally there are reasons why a 
primitive is not directly accessible (unless we haven't got around 
tackling that part of TeX)

b) if there is a need, developers are asked to initiate a discussion on 
latex-l that explains the need for an interface

c) are prepared to update their code when that interface is provided

**Comment by josephwright** [comment]
@FrankMittelbach  All certainly true: will try to write something later today

**Comment by FrankMittelbach** [comment]
Am 12.08.15 um 07:27 schrieb Bruno Le Floch:
> Thanks. Can you also include the following mention? That when people
> want an internal from another package (e.g.,
> |\__prg_variable_get_type:N|) they should copy its definition into their
> package, so that if the implementation changes their package does not
> break. And they should probably tell the other package writer (e.g., us)
> so that he/she knows that her/his code is used hence should be given a
> public interface (e.g., rename |\__prg_...| to |\prg_...|).

agreed. And their first thought should be: is the approach of using the 
internal really needed or is there a better interface provided after all

**Comment by blefloch** [comment]
For the record: in his particular case (getting the part of a csname after the last `_`) there is no better interface defined.
