### ISSUE TITLE
Interface for \endlinechar, \newlinechar

### ISSUE THREAD

**Issue by blefloch** [latex3/svn-mirror#48]
An interface for `\tex_endlinechar:D` and `\tex_newlinechar:D` is needed when manipulating `xparse` verbatim arguments with more than one line. Typically, one has to do

    \RequirePackage{xparse}
    \ExplSyntaxOn
    \DeclareDocumentCommand{\foo}{+v}
      {
        \tl_rescan:nn
          {
             \int_set:Nn \tex_newlinechar:D {13} % convert the input ^^M to new lines.
             \int_set:Nn \tex_endlinechar:D {13} % convert the new lines into ^^M when reading.
          }
          {#1}
      }
    \ExplSyntaxOff
    \foo+Some normal text.

    More of it.+

Without the settings to `\tex_newlinechar:D` and `\tex_endlinechar:D`, the text after the first `^^M` is lost, since `\scantokens` is seen as a single-liner, and catcode `5` characters tell TeX to gobble anything that follows in the line.

**Comment by josephwright** [comment]
Use cases?

**Comment by blefloch** [comment]
For the record, here are the values `\endlinechar` is given in various packages in TeXLive: -1 (to avoid worrying about commenting end-line spaces), 10 (i.e. equal to `\newlinechar` just before `\scantokens`), 13 (standard), 32 (in ExplSyntax in `expl3`), 59 (i.e. `=`, no idea why).

Concerning the interface to `\newlinechar` and `\endlinechar` that we need to provide in relation to `\tl_rescan:nn` (issue #154), I think it is covered by my next commit in preparation, so I am closing this issue too.
