### ISSUE TITLE
\lua_now:x and other x-variants documented as expandable

### ISSUE THREAD

**Issue by blefloch** [latex3/svn-mirror#94]
The `l3luatex` module currently features 4 x-type variants of expandable functions, namely `\lua_now:x`, `\lua_now_x:x`, `\lua_shipout:x`, and `\lua_shipout_x:x`.  Those appear in the documentation source as

    % \begin{function}[EXP]{\lua_now:n, \lua_now:x}

The issue is that `\lua_now:x` is then also marked as expandable.  Changing the markup to

    % \begin{function}[EXP]{\lua_now:n}
    % \begin{function}{\lua_now:x}

gives an ugly result, since the two functions are not seen as variants of each other anymore.

**Comment by josephwright** [comment]
This got fixed a while ago by removing the functions: I probably should address that but that is a separate issue!
