### ISSUE TITLE
Are cctab local or global?

### ISSUE THREAD

**Issue by blefloch** [latex3/svn-mirror#95]
Category code tables `cctab`, implemented in `l3luatex` (using `luatex.sty` under the hood) behave neither globally nor locally.  As far as I can tell, the catcode assignments are local, and the stack manipulations are global.

    \RequirePackage{expl3}
    \ExplSyntaxOn

    \cctab_new:N \l_my_cctab
    \cctab_gset:Nn \l_my_cctab { \char_set_catcode_other:n { `# } }

    \cs_show:N # % Macro
    \cctab_begin:N \l_my_cctab
    {
      \cs_show:N # % Other
      \cctab_end:
      \cs_show:N # % Macro
    }
    \cs_show:N # % Other since catcode assignments are local
    \cctab_end: % error since the stack was globally popped.

    \tex_end:D

Both an all-local and an all-global versions can be used.  We can also be stricter, checking that the stack was popped in the same group as it was pushed, but I think this is overly constraining.

I'm in favor of an all-local version, which allows code such as

    \DeclareDocumentEnvironment { verbatim } { } { \cctab_begin:N \l_verbatim_cctab } { }

with no explicit `\cctab_end:`.  Because of this kind of code, I'd like to rename `\cctab_begin:N` to `\cctab_push:N`, and `\cctab_end:` to `\cctab_pop:`, which would make the code above less odd.  Also, the names `\cctab_begin:N` and `\cctab_end:` seem to imply a group, but they don't actually introduce one.

**Comment by josephwright** [comment]
We revisited the entire LuaTeX business a while ago and cut things back down to the minimum. Catcode tables got removed and for the moment are not present at all. Based on ongoing ideas in https://github.com/josephwright/ltluatex we may have a better catcode table stack available generally soon in any case.

At present there is nothing to do here so closing.
